WITH mappings(asset_id, source_asset_id, confidence, metadata) AS (
  VALUES
    ('APE', 'apecoin', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"ApeCoin"}'::jsonb),
    ('APT', 'aptos', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Aptos"}'::jsonb),
    ('BOME', 'book-of-meme', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"BOOK OF MEME"}'::jsonb),
    ('MEME', 'memecoin-2', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Memecoin"}'::jsonb),
    ('FLOKI', 'floki', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"FLOKI"}'::jsonb),
    ('MEW', 'cat-in-a-dogs-world', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"cat in a dogs world"}'::jsonb),
    ('ETH', 'ethereum', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Ethereum"}'::jsonb),
    ('TAO', 'bittensor', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Bittensor"}'::jsonb),
    ('BONK', 'bonk', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Bonk"}'::jsonb),
    ('WLD', 'worldcoin-wld', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Worldcoin"}'::jsonb),
    ('BTC', 'bitcoin', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Bitcoin"}'::jsonb),
    ('tBTC', 'tbtc', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"tBTC"}'::jsonb),
    ('WBTC.b', 'arbitrum-bridged-wbtc-arbitrum-one', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Arbitrum Bridged WBTC (Arbitrum One)"}'::jsonb),
    ('DOGE', 'dogecoin', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Dogecoin"}'::jsonb),
    ('EIGEN', 'eigenlayer', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"EigenCloud (prev. EigenLayer)"}'::jsonb),
    ('LTC', 'litecoin', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Litecoin"}'::jsonb),
    ('SHIB', 'shiba-inu', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Shiba Inu"}'::jsonb),
    ('SOL', 'solana', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Solana"}'::jsonb),
    ('SUI', 'sui', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Sui"}'::jsonb),
    ('SEI', 'sei-network', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Sei"}'::jsonb),
    ('STX', 'blockstack', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Stacks"}'::jsonb),
    ('UNI', 'uniswap', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Uniswap"}'::jsonb),
    ('LINK', 'chainlink', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Chainlink"}'::jsonb),
    ('ARB', 'arbitrum', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Arbitrum"}'::jsonb),
    ('XRP', 'ripple', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"XRP"}'::jsonb),
    ('USDC', 'usd-coin', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"USDC"}'::jsonb),
    ('USDC.e', 'bridged-usdc', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Bridged USDC"}'::jsonb),
    ('USDT', 'tether', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Tether"}'::jsonb),
    ('DAI', 'dai', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Dai"}'::jsonb),
    ('BNB', 'binancecoin', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"BNB"}'::jsonb),
    ('ATOM', 'cosmos', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Cosmos Hub"}'::jsonb),
    ('NEAR', 'near', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"NEAR Protocol"}'::jsonb),
    ('AAVE', 'aave', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Aave"}'::jsonb),
    ('AVAX', 'avalanche-2', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Avalanche"}'::jsonb),
    ('OP', 'optimism', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Optimism"}'::jsonb),
    ('ORDI', 'ordinals', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"ORDI"}'::jsonb),
    ('TIA', 'celestia', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Celestia"}'::jsonb),
    ('TRX', 'tron', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"TRON"}'::jsonb),
    ('TON', 'the-open-network', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Toncoin"}'::jsonb),
    ('GMX', 'gmx', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"GMX"}'::jsonb),
    ('WIF', 'dogwifcoin', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"dogwifhat"}'::jsonb),
    ('PEPE', 'pepe', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Pepe"}'::jsonb),
    ('PENDLE', 'pendle', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Pendle"}'::jsonb),
    ('wstETH', 'arbitrum-bridged-wsteth-arbitrum', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Arbitrum Bridged wstETH (Arbitrum)"}'::jsonb),
    ('USDe', 'ethena-usde', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Ethena USDe"}'::jsonb),
    ('SATS', 'sats-ordinals', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"SATS (Ordinals)"}'::jsonb),
    ('POL', 'polygon-ecosystem-token', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"POL (ex-MATIC)"}'::jsonb),
    ('ADA', 'cardano', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Cardano"}'::jsonb),
    ('XLM', 'stellar', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Stellar"}'::jsonb),
    ('BCH', 'bitcoin-cash', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Bitcoin Cash"}'::jsonb),
    ('DOT', 'polkadot', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Polkadot"}'::jsonb),
    ('ICP', 'internet-computer', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Internet Computer"}'::jsonb),
    ('RENDER', 'render-token', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Render"}'::jsonb),
    ('FIL', 'filecoin', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Filecoin"}'::jsonb),
    ('INJ', 'injective-protocol', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Injective"}'::jsonb),
    ('DYDX', 'dydx-chain', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"dYdX"}'::jsonb),
    ('TRUMP', 'official-trump', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Official Trump"}'::jsonb),
    ('MELANIA', 'melania-meme', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Melania Meme"}'::jsonb),
    ('ENA', 'ethena', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Ethena"}'::jsonb),
    ('FARTCOIN', 'fartcoin', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Fartcoin"}'::jsonb),
    ('AI16Z', 'ai16z', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"ai16z"}'::jsonb),
    ('ANIME', 'anime', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Animecoin"}'::jsonb),
    ('LDO', 'lido-dao', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Lido DAO"}'::jsonb),
    ('BERA', 'berachain-bera', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Berachain"}'::jsonb),
    ('VIRTUAL', 'virtual-protocol', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Virtuals Protocol"}'::jsonb),
    ('PENGU', 'pudgy-penguins', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Pudgy Penguins"}'::jsonb),
    ('ONDO', 'ondo-finance', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Ondo"}'::jsonb),
    ('FET', 'fetch-ai', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Artificial Superintelligence Alliance"}'::jsonb),
    ('AIXBT', 'aixbt', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"aixbt"}'::jsonb),
    ('CAKE', 'pancakeswap-token', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"PancakeSwap"}'::jsonb),
    ('S', 'sonic-3', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Sonic"}'::jsonb),
    ('JUP', 'jupiter-exchange-solana', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Jupiter"}'::jsonb),
    ('HYPE', 'hyperliquid', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Hyperliquid"}'::jsonb),
    ('MKR', 'maker', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Maker"}'::jsonb),
    ('OM', 'mantra-dao', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"MANTRA [Old]"}'::jsonb),
    ('DOLO', 'dolomite', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Dolomite"}'::jsonb),
    ('ZRO', 'layerzero', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"LayerZero"}'::jsonb),
    ('CRV', 'curve-dao-token', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Curve DAO"}'::jsonb),
    ('MOODENG', 'moo-deng', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Moo Deng"}'::jsonb),
    ('XMR', 'monero', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Monero"}'::jsonb),
    ('PI', 'pi-network', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Pi Network"}'::jsonb),
    ('PUMP', 'pump-fun', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Pump.fun"}'::jsonb),
    ('MNT', 'mantle', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Mantle"}'::jsonb),
    ('SPX6900', 'spx6900', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"SPX6900"}'::jsonb),
    ('ALGO', 'algorand', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Algorand"}'::jsonb),
    ('HBAR', 'hedera-hashgraph', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Hedera"}'::jsonb),
    ('CRO', 'crypto-com-chain', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Cronos"}'::jsonb),
    ('OKB', 'okb', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"OKB"}'::jsonb),
    ('CVX', 'convex-finance', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Convex Finance"}'::jsonb),
    ('KAS', 'kaspa', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Kaspa"}'::jsonb),
    ('AERO', 'aerodrome-finance', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Aerodrome Finance"}'::jsonb),
    ('BRETT', 'based-brett', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Brett"}'::jsonb),
    ('WLFI', 'world-liberty-financial', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"World Liberty Financial"}'::jsonb),
    ('WELL', 'moonwell-artemis', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Moonwell"}'::jsonb),
    ('VVV', 'venice-token', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Venice Token"}'::jsonb),
    ('MORPHO', 'morpho', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Morpho"}'::jsonb),
    ('ZORA', 'zora', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Zora"}'::jsonb),
    ('KTA', 'keeta', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Keeta"}'::jsonb),
    ('XPL', 'plasma', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Plasma"}'::jsonb),
    ('ASTER', 'aster-2', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Aster"}'::jsonb),
    ('0G', 'zero-gravity', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"0G"}'::jsonb),
    ('AVNT', 'avantis', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Avantis"}'::jsonb),
    ('LINEA', 'linea', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Linea"}'::jsonb),
    ('SKY', 'sky', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Sky"}'::jsonb),
    ('ZEC', 'zcash', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Zcash"}'::jsonb),
    ('MON', 'monad', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Monad"}'::jsonb),
    ('AR', 'arweave', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Arweave"}'::jsonb),
    ('DASH', 'dash', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Dash"}'::jsonb),
    ('SYRUP', 'syrup', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Maple Finance"}'::jsonb),
    ('JTO', 'jito-governance-token', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Jito"}'::jsonb),
    ('CHZ', 'chiliz', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Chiliz"}'::jsonb),
    ('IP', 'story-2', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Story"}'::jsonb),
    ('LIT', 'lighter', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Lighter"}'::jsonb),
    ('CC', 'canton-network', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Canton"}'::jsonb),
    ('MET', 'meteora', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"Meteora"}'::jsonb),
    ('MEGA', 'megaeth', 'reviewed', '{"method":"coingecko_symbol_search","coingecko_name":"MegaETH"}'::jsonb)
)
INSERT INTO "asset_source_mappings" (
  "asset_id",
  "source",
  "source_asset_id",
  "confidence",
  "metadata",
  "updated_at"
)
SELECT
  mappings.asset_id,
  'coingecko',
  mappings.source_asset_id,
  mappings.confidence,
  mappings.metadata,
  now()
FROM mappings
JOIN "assets" ON "assets"."asset_id" = mappings.asset_id
WHERE "assets"."source" = 'gmx'
ON CONFLICT ("asset_id", "source") DO UPDATE SET
  "source_asset_id" = excluded."source_asset_id",
  "confidence" = excluded."confidence",
  "metadata" = excluded."metadata",
  "updated_at" = now();
